# syntax version.
version: "3.7"

# services list.
services:
  # base image
  imagick:
    image: "build/imagick"
    build:
      context: "./"
      args:
        PHP_VERSION: ${PHP_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
        IMAGICK_VERSION: ${IMAGICK_VERSION}
